### ISSUE TITLE
Code comments styled in pdf but not html

### ISSUE THREAD

**Issue by joeyklee** [nature-of-code/noc-book-2-archive#29]
@shiffman - this is one of the open tasks correct?

<img width="1264" alt="Screen Shot 2019-06-25 at 13 52 57" src="https://user-images.githubusercontent.com/3622055/60121264-adc41f00-9750-11e9-9111-c5b1d18dbb5d.png">
<img width="1516" alt="Screen Shot 2019-06-25 at 13 53 03" src="https://user-images.githubusercontent.com/3622055/60121269-aef54c00-9750-11e9-93f4-766baf1fa9e6.png">

**Comment by shiffman** [comment]
Yes! The HTML code snippets should include some kind of design treatment (box?), syntax highlighting, and floating comments to the side. For the original book, we also implemented a "raw view" but this could also be replaced by a "copy code" button. (The issue is that the comments floating to the side made copy/paste not work.)

I could probably live without the comments floating to the side if that becomes too much of a road block, but ideally we'd do something more than just greyed out code comments? I have never found these super helpful when "reading code" in a book context? Then again, it's 2019, maybe we've all adapted to code comments by now. 😂

Nothing about the below has to be kept the same way, just noting for reference.

<img width="830" alt="Screen Shot 2019-06-25 at 1 59 28 PM" src="https://user-images.githubusercontent.com/191758/60121608-799d2e00-9751-11e9-888a-2e05739743c8.png">

**Comment by joeyklee** [comment]
@shiffman - got it. Hmm strange why the code-split styles aren't being applied to the html. I'll see what I can find here.

**Comment by joeyklee** [comment]
Ah I see what was funky. 

in our `magicbook.json` we were pointing to pre-built css files. I will make a PR to ensure we are always pointing to our .scss files for the latest  styles.

**Comment by joeyklee** [comment]
<img width="1264" alt="Screen Shot 2019-06-25 at 14 19 01" src="https://user-images.githubusercontent.com/3622055/60122965-59bb3980-9754-11e9-872e-a4c8378424ec.png">

**Comment by joeyklee** [comment]
resolved by https://github.com/nature-of-code/noc-book-2/pull/34
