### ISSUE TITLE
visual consistency of examples

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2-archive#80]
Over the years the color palette for the examples has gone through various iterations. If I recall correctly, for the print book, having a white background (and black outlines, gray fills) makes the most sense for print screenshots. The design of the HTML version might be different. 

Print:
```javascript
background(255);
stroke(0);
fill(127);
```
![print](https://user-images.githubusercontent.com/191758/62224738-2720e400-b385-11e9-8618-8a1720e79e82.png)

Website:
```javascript
background(0);
stroke(255);
fill(127);
```
![web](https://user-images.githubusercontent.com/191758/62224759-2daf5b80-b385-11e9-8eba-bd485b9a4c41.png)

But I would LOVE design advice and thoughts here. . . and maybe best to not have two different color palettes?

Exception are also of course allowed throughout the book!

**Comment by BrandlMax** [comment]
In general, as a designer I would always recommend consistency. Unless there is really a good reason for a better reader/user experience. So from the choice of the font to the background color of the example. In this case, a white background in print makes a lot of sense, so why not use it on the website as well? 

When we get to visual consistency 🙈 Is there a way for syntax highlighting so that the appearance of the code is consistent here (or even better😅)? When I read nature of code as EPUB back then, it was sometimes difficult to follow the grey, colorless lines of code. I think it would not only help to understand the code but also make it fun to read 🌈

**Comment by shiffman** [comment]
@jasongao97 would be great if you could think about this as you go through the examples!

**Comment by shiffman** [comment]
Now tracking in https://github.com/nature-of-code/book-website-2nd-edition/issues/90
